#!/bin/bash

export POSIXLY_CORRECT=yes

print_help() 
{
    echo "mole -h"
    echo "mole [-g GROUP] FILE"
    echo "mole [-m] [FILTERS] [DIRECTORY]"
    echo "mole list [FILTERS] [DIRECTORY]"   
    echo "mole secret-log [-b DATE] [-a DATE] [DIRECTORY1 [DIRECTORY2 [...]]]"
}

group()
{
    echo "$FILE|$GROUP|$DATE"  >> $MOLE_RC
}

open () 
{
    awk -v, -F, '{|, s}'
}

editor()
{
    echo $EDITOR $FILE
}

list () 
{
    echo "list"
}

DATE=$(date)
FILE=""
GROUP="-"
FILTER=""

# check if utillity realpath is available
if ! [ -x "$(command -v realpath)" ]
then
    echo "<realpath> could not be found"
    exit 1
fi

# look for MOLE_RC, export MOLE_RC=$HOME/.config/molerc
PATH=""
if [ -n $MOLE_RC ]; then
    if [ ! -e $MOLE_RC ]; then
        touch $MOLE_RC
    fi
else 
    exit 1
fi

# look for EDITOR, VISUAL, vi
EDITOR=""
if [ -e "EDITOR" ]; then 
    EDITOR="EDITOR"    
elif [ -e "VISUAL" ]; then
    EDITOR="VISUAL"
else
    EDITOR="vi"
fi

while [ "$#" -gt 0 ]; do
    case "$1" in
        -h)
            print_help
            exit 0
            ;;
        -g)
            FILTER=$1
            GROUP=$2
		    FILE=$3
            shift
            shift
            shift
            group
            ;;
        -m)
            FILTERS=$1
            DIRECTORY=$2
            shift
            shift
            shift
            editor
            ;;  
        -list)
            FILTERS=$1
            DIRECTORY=$2
            shift
            shift
            list
            ;;
        -)
            echo "nothing, just open"
            exit 0
            ;;
        *)
            echo "Unknown command"
            exit 1
    esac
done
