#!/bin/bash

export POSIXLY_CORRECT=yes

print_help() {
    echo "Usage: "
    echo " mole [FILTERS] [DIRECTORY]"
    echo " "
    echo "COMANDS:"
    echo "  mole list [FILTERS] [DIRECTORY]     opens certain file"
    echo " "
    echo "FILTERS:"
    echo "  [-h]                                prints help"
    echo "  [-g GROUP1[,GROUP2[,...]]] FILE     add file to a GROUP"
    echo "  [-m] [FILTERS] [DIRECTORY]          opens the file thah was edited most frequently"
    echo "  [-a DATE] YYYY-MM-DD                lists all the files edited after certain date"
    echo "  [-b DATE] YYYY-MM-DD                lists all the files edited begore certain date"
}

group() {
    echo "$FILE|$GROUP|$DATE" >>"$MOLE_RC"
}

open() {
    cat "$MOLE_RC" | date_before | date_after | awk -v, -F, '{|, s}'
}

editor() {
    echo $EDITOR $FILE
}

list() {
    cat "$MOLE_RC" | date_before | date_after
}

secret_log() {
    echo "secret log"
}

date_before() {
    awk -F '|' -v date="$DATE_BEFORE" '{if (FNR>1 && $3<date) print}'
}

date_after() {
    awk -F '|' -v date="$DATE_AFTER" '{if (FNR>1 && $3>date) print}'
}

DATE=$(date +%F_%H-%M-%S)
DATE_AFTER="0000-00-00"
DATE_BEFORE="9999-99-99" 
FILE=""
GROUP="-"
FILTER=""
DIRECTORY=""
COMMAND=""

# check if utillity realpath is available
if ! [ -x "$(command -v realpath)" ]; then
    echo "<realpath> could not be found"
    exit 1
fi

# look for MOLE_RC, export MOLE_RC=$HOME/.config/molerc
if [ -n "$MOLE_RC" ]; then
    if [ ! -e "$MOLE_RC" ]; then
        touch "$MOLE_RC"
    fi
else
    echo "MOLE_RC can't be found"
    exit 1
fi

# look for EDITOR, VISUAL, vi
EDITOR=""
if [ -e "EDITOR" ]; then
    EDITOR="EDITOR"
elif [ -e "VISUAL" ]; then
    EDITOR="VISUAL"
else
    EDITOR="vi"
fi

while [ "$#" -gt 0 ]; do
    case "$1" in
    secret-log | list)
        COMMAND=$1
        shift
        ;;
    -h)
        print_help
        exit 0
        ;;
    -g)
        FILTER=$1
        GROUP=$2
        FILE=$3
        shift
        shift
        shift
        group
        ;;
    -m)
        FILTER=$1
        DIRECTORY=$2
        shift
        shift
        ;;
    -a)
        FILTER=$1
        DATE_AFTER=$2
        shift
        shift
        ;;
    -b)
        FILTER=$1
        DATE_BEFORE=$2
        shift
        shift
        ;;
    *)
        echo Error: Unknown Command
        exit 0
        ;;
    esac
done

case "$COMMAND" in
list)
    list
    ;;
secret-log)
    secret_log
    ;;
*)
    echo Error: Unknown Command
    exit 0
    ;;
esac
